services:
  frontend:
    container_name: squadrun-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - squadrun_net
    restart: always

networks:
  squadrun_net:
    external: true
    name: squad-run_squadrun_net
